name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run a one-line script
        run: ./gradlew clean build

      - name: Copy to dist folder
        run: |
          mkdir dist
          cp ./build/libs/*.jar dist/app.jar
          cp ./app.sh dist/app.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - name: Start
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd dist
          sh app.sh restart
      - name: Health
        run: |
          cd dist
          sh app.sh health



